name: Scrape Agenda On-Demand

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python scraper.py --output agenda.csv

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: agenda-csv
          path: agenda.csv
