name: Scrape Agenda On-Demand

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python scraper.py --output agenda.csv

      - name: Push agenda.csv to its own branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # create (or reset) the output branch
          git fetch origin
          git checkout -B agenda-output

          # commit & force-push
          git add agenda.csv
          git commit -m "Auto-update scraped agenda.csv" || echo "No changes to commit"
          git push origin agenda-output --force

      - name: Done
        run: echo "✅ agenda.csv has been pushed to the 'agenda-output' branch. You can view/download it here: https://github.com/${{ github.repository }}/blob/agenda-output/agenda.csv"
